apiVersion: v1
kind: Namespace
metadata:
  name: jquery
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jquery-deployment
  namespace: jquery
  labels:
    app: jquery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jquery
  template:
    metadata:
      labels:
        app: jquery
    spec:
      containers:
      - name: jquery
        image: 306518615214.dkr.ecr.us-east-2.amazonaws.com/jquery:1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: jquery-svc
  namespace: jquery
spec:
  selector:
    app: jquery
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

